### ISSUE TITLE
Make it work without Docker, for Windows 10 Home

### ISSUE THREAD

**Issue by feinstein** [awslabs/aws-sam-cli#1071]
Some of us have a laptop that came with Windows 10 Home and Docker only works with Windows 10 Pro or Enterprise. Could you make SAM Local work for Windows 10 Home?

**Comment by jfuss** [comment]
@feinstein Currently SAM CLI is fairly dependent upon docker (for build and invoke) and right now I don't think moving away is completely possible. The main reason is that we need a way for us to replicate the Lambda environment locally, which docker does a decent job at.

You can check out this [docker forum](https://forums.docker.com/t/installing-docker-on-windows-10-home/11722/44), which has some people being successful in installing Docker for Windows. The other option is to install Docker Toolbox instead of Docker for Windows. 

Closing this issue since, we are heavily dependent upon Docker and cannot reliably remove this dependency.

**Comment by feinstein** [comment]
I understand, thank you anyway :)

**Comment by feinstein** [comment]
For anyone that found this issue, I was able to easily upgrade my Windows 10 Home to Enterprise, simply providing an old Windows 8 Pro Product Key. 

Windows 10 will update to Windows 7 and 8 versions of old computers if you provide their Product Keys, if this Product Key wasn't activated before on any Windows 10 computer (after it is, the Product Key becomes tied to the hardware of your computer at Microsoft's servers).

**Comment by sumit1khandelwal** [comment]
Docker for Windows is now paid, Is there any other free way to debug lambda function on local. I know only one way like serverless framework https://www.serverless.com/ running on local. But I want to do by using aws sam cli otherwise I need to change my template file. Please suggest me.
