### ISSUE TITLE
Upgrade pyyaml due to a potential security vulnerability

### ISSUE THREAD

**Issue by bhuang149** [awslabs/aws-sam-cli#1150]
**Description:**

CVE-2017-18342 (Click [here](https://nvd.nist.gov/vuln/detail/CVE-2017-18342) for more information)

In PyYAML before 4.1, the yaml.load() API could execute arbitrary code. In other words, yaml.safe_load is not used.

Since `aws-sam-cli` requires `pyyaml` to be `~=3.12`, as a client, I won't be able to update `pyymal` to be `>4.1`. Thus, I am wondering if you guys could upgrade the version of `pyyaml` for `aws-sam-cli`

**Output of `sam --version`**: SAM CLI, version 0.8.1

**Comment by jfuss** [comment]
@bhuang149 We are aware and are not impacted by this as we use the safe_load method. 

What OS are you on and how have you installed the CLI? Using our installers gives you isolation so you should never run into conflicts. If you are using pip, I encourage you not to and move to our installers. If you really want to use pip, you should be using a venv and create the isolation yourself.

**Comment by bhuang149** [comment]
@jfuss Hi Jacob,

Thank you for your reply.

I installed the CLI using pip on a macOS machine, and I have created the isolation.

The reason why I submitted this issue because I am actually using `pipenv` and GitHub always sends security alerts to me because it detected `pyyaml~=3.12` in Pipfile.lock. For those who also use `pipenv`, they may also see this alert complaining about `pyyaml~=3.12`.

**Comment by Zangror** [comment]
Hi @jfuss,

Using poetry to manage my virtual environment, I cannot update other libraries because they depends on newer version of PyYaml and aws-sam-cli doesn't.

> [SolverProblemError]
Because aws-sam-cli (0.17.0) depends on PyYAML (>=3.12,<4.0)
 and sceptre (2.1.0) depends on PyYaml (>=4.2b1,<5.0), aws-sam-cli (0.17.0) is incompatible with sceptre (2.1.0).
So, because datalake depends on both sceptre (=2.1.0) and aws-sam-cli (=0.17.0), version solving failed.

If you are not impacted, could it be possible to update PyYaml because it's blocking us.

Thanks 😄

**Comment by jfuss** [comment]
@Zangror This shouldn't be an issue for you unless you are using pip to install the CLI. The team recommends using our installers instead of pip to provide isolation, so the path forward is to move away from pip to install the CLI.

**Comment by awood45** [comment]
This has been upgraded, and that upgrade will go out with the next release.
