### ISSUE TITLE
Enable verbose logging

### ISSUE THREAD

**Issue by sanathkr** [awslabs/aws-sam-cli#122]
When the CLI doesn't behave as expected (Ex: CodeUri is pointing to a non-existent folder), there is no way of enabling verbose logging to find the problem. This task is to:

1. Add more debug logging using a real logging library
2. Provide a flag to enable verbose logging

**Comment by purefan** [comment]
What you are requesting is a proper validator, not just a syntax validator which is what we have now.
My suggestion is that you define test cases for this validator so we can work against a set of expected results, for example:
> Given the following scenario <path-to-folder-with-template.yml-and-folders> the test must fail because CodeUri points to a non existent location

Then we can set up the unit tests that fulfill these expectations and fix it in the code.

**Comment by jhovell** [comment]
I'm not sure @sanathkr is specifically asking for a validator (though I'm not arguing that might be a good feature as well, but maybe make a separate issue with an accurate topic name).

I'm posting this here because I think it falls under a use case to enable verbose logging. I am attempting to get SAM Local working as a docker container. The only output I am able to get from sam local is:
```
17:53:10 sam-local> 2017/10/25 00:53:10 Invoking myapp.EventHandler::handleRequest (java8)
17:53:10 sam-local> 2017/10/25 00:53:10 Decompressing /mnt/sam/target/myapp.jar
17:53:12 sam-local> 2017/10/25 00:53:11 Connecting container 39914ad7d10f6b4c2124ea37409f5920e09915d66fbe096b4a9e32e20617d73c to network myapp
17:53:12 sam-local> 2017/10/25 00:53:12 Function returned an invalid response (must include one of: body, headers or statusCode in the response object): invalid character 'E' looking for beginning of value
```

It returns a 502 with no payload. No idea how to go about debugging this... invalid character X looking for beginning of value seems to be an incredibly generic go parse error & there is no stack trace or anything to help start finding the cause of this error or print the payload that starts with E.

A verbose logging feature would be very handy for debugging or troubleshooting various sam local issues.

**Comment by purefan** [comment]
@jhovell that error [is documented behavior](https://github.com/awslabs/aws-sam-local/blob/develop/README.md):

> By default, SAM uses Proxy Integration and expects the response from your Lambda function to include one or more of the following: statusCode, headers and/or body.

> If your function does not return a valid Proxy Integration response then you will get a HTTP 500 (Internal Server Error) when accessing your function. SAM Local will also print the following error log message to help you diagnose the problem:
> 
> ERROR: Function ExampleFunction returned an invalid response (must include one of: body, headers or statusCode in the response object)

I also advise on reading the Debugging section, for example I have set up VSCode to use step debugging for sam local

**Comment by jhovell** [comment]
@purefan are you talking about debugging SAM local or your Java, Python, Node application? I do not see any documentation about the former. Are you referring to different documentation?

https://github.com/awslabs/aws-sam-local#debugging-applications

"invalid character 'E' looking for beginning of value" is a mangled version of a Docker API error that SAM Local go code attempts to parse as JSON (see issue this is linked to above) due to SAM Local making assumptions about logging drivers. Not sure step debugging my Java or Python app is going to help get to the bottom of that but maybe I don't understand. Can you explain further? The original poster @sanathkr makes it sound like he is trying to debug SAM local / template.yaml issues and not his Lambda app. I believe that use case of debugging a user's app is well covered by use of a remote debugger.

**Comment by purefan** [comment]
@jhovell this behavior is programming language agnostic, your response has to include a body, a header or a statusCode.

VSCode step debugger is a remote debugger

Your issue suggests that you need even more debugging info, but I think you already have all the info you need to find out what is _less than perfect_ in your code:
- The error reported is `Function returned an invalid response (must include one of: body, headers or statusCode in the response object)`
- The documentation says that "If your function does not return a valid Proxy Integration response then you will get a HTTP 500 "
- And you have step debugging as you pointed out

So you can debug why your app is returning a 500 error instead of a proper response. Unless Im confusing things I think that step debugging why your app is not returning a proper response would lead to fixing this

**Comment by jhovell** [comment]
@purefan The SAM Local fails before the lambda launches & my code is never even run. The problem has nothing to do with the lambda function code but with the configuration of Docker, specifically logging drivers. SAM Local attempts to de-serialize the stdout from the container as the result of the Lambda. A Node or Java debugger is not going to help here as it will never get triggered.

Just put the following in your /etc/sysconfig/docker and restart docker and you'll see that SAM Local no longer works.
```
OPTIONS='--log-driver=awslogs --log-opt awslogs-group=/some/loggroup --log-opt awslogs-region=us-east-1'
``` 
See this issue if you need more detail.

https://github.com/awslabs/aws-sam-local/issues/182

Where having better SAM Local debugging or logging would help is to print the std out/err from the container on line 570 rather than the error of the unmarshalling. " invalid character 'E' looking for beginning of value" is not very helpful in hunting down the problem.

https://github.com/awslabs/aws-sam-local/blob/df8479ba2d537a7d94d88c52f9d6ccfd02f768e1/runtime.go#L567

The root of the problem is the line ```ioutil.ReadAll(stdoutTxt)``` which isn't a valid thing to do for certain Docker logging drivers, ironically in this case awslogs.

Let me know if this still isn't making sense.

**Comment by sanathkr** [comment]
Not relevant anymore because the new release already does https://github.com/awslabs/aws-sam-cli/releases/tag/v0.3.0
