### ISSUE TITLE
Adding new lambda function or Update Function Code fails during SAM build

### ISSUE THREAD

**Issue by jconwell** [awslabs/aws-sam-cli#1327]
**Description:**

I'm using PyCharm and the SAM plugin.  When adding a second lambda function (via "Create new AWS Lambda..." context menu) or calling "Update Function Code" a SAM build error is thrown.

**Steps to reproduce the issue:**
1. Right click Lambda in AWS Explorer window, and create 1 lambda function (works, yay)
2. Right click Lambda in AWS Explorer window, and create 2nd lambda function
3. SAM build error is reported in the Build Output window

**Observed result:**
/usr/local/bin/sam build --template /Users/xxx/projects/xxx/.aws-sam/build/template.yaml --build-dir /Users/xxx/projects/xxx/.aws-sam/build Function
2019-08-08 15:08:06 Building resource 'Function'
2019-08-08 15:08:06 Running PythonPipBuilder:ResolveDependencies

Build Failed
Error: PythonPipBuilder:ResolveDependencies - Requirements file not found: /Users/xxx/projects/xxx/.aws-sam/build/Function/requirements.txt

**Expected result:**
The zip file for the lambda code is packaged together and pushed to the specified S3 bucket, and a lambda function is created in AWS Lambda

**Word around:**
The build error states that it can't fine the requirements.txt file. If I manually create the .aws-sam/build/Function/ folder and copy the requirements.txt into it, creating the Lambda function works just fine.

**Comment by jfuss** [comment]
@jconwell Do not manually create `.aws-sam`, this directory is generated by `sam build`. You need to place the `requirements.txt` file in the directory of your function (`CodeUri`). This is a requirement of build and we do have an open issue to make this no longer required (#784). 

Closing as this is an issue with the setup and build requires the file to be places in the CodeUri/Code directory or overwritten with the `--manifest` option.

**Comment by jconwell** [comment]
I did not manually create the `.aws-sam` folder, or the `build` sub-folder. These were generated when creating the first lambda function (I assume). It is when I create the second lambda function (I was hoping to have several in one project, not just one) I get the error.

**Comment by jconwell** [comment]
@jfuss I really don't think this issue should be closed. Please don't make assumptions to what I did and close the ticket.

**Comment by jfuss** [comment]
@jconwell My comment about do not manually create `.aws-sam` was in response to "If I manually create the .aws-sam/build/Function/ folder and copy the requirements.txt" and goes for anything under that folder. This folder is generated and maintained by the CLI, changing out of band can and may result in weird behavior, so please don't do it.

You are pass the built template into build. Instead of `sam build --template /Users/xxx/projects/xxx/.aws-sam/build/template.yaml --build-dir /Users/xxx/projects/xxx/.aws-sam/build Function`, it should just be `sam build`. This takes care of everything for you. Build should be done on the source not on the already generated build artifacts.

As previously stated, you need a requirements file in all CodeUri directories unless passed/overwritten with `--manifest`.

I am happy to keep the conversation going but there is no action from us and would prefer to keep this closed unless that changes.
