### ISSUE TITLE
AWS SAM does not accept a local code URI

### ISSUE THREAD

**Issue by westlakem** [awslabs/aws-sam-cli#1400]
### Description

sam is refusing to deploy even the hello world example

### Steps to reproduce

create a new sam project, and attempt to deploy it.

1. run sam init
2. run sam deploy --template-file template.yaml --stack-name my-stack

### Observed result

Waiting for changeset to be created..

Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [HelloWorldFunction] is invalid. 'CodeUri' is not a valid S3 Uri of the form "s3://bucket/key" with optional versionId query parameter.
Exception: Command '['aws.exe', 'cloudformation', 'deploy', '--stack-name', 'my-stack', '--template-file', 'template.yaml']' returned non-zero exit status 255.

### Expected result

the project to deploy

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. `sam --version`: 0.21.0

**Comment by jfuss** [comment]
@westlakem The key thing you are missing is the `sam package` command, which takes the local references (in your case `CodeUri`), zips, and uploads them to S3 to be used in the deployment. Instructions and guides are provided in the READMEs of our inits.

Closing, since before deploy you need to run package.
