### ISSUE TITLE
Java Runtime Sample Crashes In Lambda Class not found: helloworld.App

### ISSUE THREAD

**Issue by michaelgamazon** [awslabs/aws-sam-cli#1569]
### Description

The sample Java8 Lambda function that sam creates when calling sam init -r java8 works locally but does not work in Lambda. It throws an error:
{
  "errorMessage": "Class not found: helloworld.App",
  "errorType": "java.lang.ClassNotFoundException"
}

### Steps to reproduce

sam init -r java8 -n java-import-ssl-cert
cd java-import-ssl-cert/
sam build
sam package --template-file template.yaml --output-template-file serverless-output.yaml --s3-bucket mredactedw
sam deploy --template-file serverless-output.yaml --stack-name java8-import-ssl-cert

### Observed result

sam local invoke works but when ran on Lambda it throws:
{
  "errorMessage": "Class not found: helloworld.App",
  "errorType": "java.lang.ClassNotFoundException"
}

### Expected result

I expect the function to work properly in Lambda. I also expect sam local invoke to always return the same thing as official AWS Lambda. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. `sam --version`: SAM CLI, version 0.31.1

**Comment by jfuss** [comment]
@michaelgamazon This is due to you passing `--template template.yaml` in the `sam package` command. You are telling the command to use that specific template, which as un-built functions. You should instead remove the `--template` option on `sam package` so the built template/artifacts can be properly picked up. 

Closing as this is working as expected given the template was passed to the `sam package` command.
