### ISSUE TITLE
Broken dateparser -> regex Dependency

### ISSUE THREAD

**Issue by alienfreak** [awslabs/aws-sam-cli#1679]
Hello!

We've started experiencing an issue around mid-day MST in what seems like one of your dependencies is broken during a pip3 install.

Bamboo Build Commands: 
```
apt-get install python3-pip jq -yq
pip3 install aws-sam-cli==0.30.0
```
Here is a screenshot. The error we are seeing is on the left and on the right the corresponding update made to the 'regex' dependency earlier today. (linked below)
![image](https://user-images.githubusercontent.com/12786194/71042658-9d7e7280-20e9-11ea-9aa2-0682c0c5b655.png)

Here is the update to that package that I believe is affecting the install:
https://bitbucket.org/mrabarnett/mrab-regex/commits/6ee030c10e8978bfb0f4c7f724364d955878bd3a

Any guidance is much appreciated. 
Let me know of any more information I can provide.
Thanks for your time!

**Comment by jfuss** [comment]
@alienfreak We have not seen build failures for this, so my initially guess is this is due to your system. This could be related to the versions of pip you are using or python version. Looking at the images you provided, it seems you are install into a version of python that is unsupported by us (currently only 3.6 and 3.7). 

You should be making sure you have updated pip and install into one of the supported versions. Alternatively, you can use linuxbrew to install and not have to maintain any of this yourself.

Going to close this as there doesn't appear to be an issue with SAM CLI directly. Feel free to reopen if you have upgraded python and pip and still are seeing this issue.

**Comment by alienfreak** [comment]
A fix was implemented by the regex developer here:
https://bitbucket.org/mrabarnett/mrab-regex/commits/75b3d40f096cba230c116f3583b3e8ace07f6899
Thanks for your time anyway!
