### ISSUE TITLE
Add the possibility to run --guided only when samconfig.toml is not present

### ISSUE THREAD

**Issue by nmoutschen** [awslabs/aws-sam-cli#1728]
### Describe your idea/feature/enhancement

When running `sam deploy --guided`, SAM asks questions and override ParameterOverrides values with the default ones. However, when a user runs `sam deploy` for the first time (without `samconfig.toml`), it assumes that it's operating in the default mode (where users need to specify the stack name, etc).

The idea is to have a "first run" mode when it'll ask the questions from `--guided`, saves to `samconfig.toml` and then use the values in the config file for subsequent calls.

### Proposal

This could be done via an additional flag with `--guided`, or creating a `--guided-first-run` flag.

Things to consider:
1. Will this require any updates to the [SAM Spec](https://github.com/awslabs/serverless-application-model): No

**Comment by awood45** [comment]
I understand the desire for this, and this approach was considered. The drawback of this approach, and the reason we went with `--guided` being an explicit parameter, is that making `sam deploy` default to an interactive shell when required parameters or `samconfig.toml` is missing is a breaking change.

If a customer is running on a CI/CD host, for example, the failure mode is that the command would be stuck waiting for input, potentially indefinitely. This was the motivation for the opt-in approach.

(For background, `sam init` has a different approach because we judged it unlikely that very many automated scripts would be running init.)

Thanks for the suggestion - if there's anything else we can do to make this experience easier, don't hesitate to let us know.
