### ISSUE TITLE
Divergence between sam package/deploy and generic cloudformation commands. why must I use two different sets of commands here and what is the story about overlap between these two 90% similar commands?

### ISSUE THREAD

**Issue by red8888** [awslabs/aws-sam-cli#1753]
At first sam deploy/package commands had less features then the aws cli cloudformation commands, now it seems like they have more. a lambda function is another resource so my expectation is I should be able to deploy it like any other cloudformation resource with "aws cloudformation" commands. I can do that but it doesn't work with all cloudformation cli features and the sam cli command has more features.

It seems like now I have to use "aws cloudformation package/deploy" commands to deploy templates _unless_ a template has a function in it (even if that function is only a small part of the full template) then I need to use sam package/deploy. Why wasnt that functionality just added to the cloudformation commands I use for everything else?

For example how do I get these features for my CF templates without functions: https://aws.amazon.com/blogs/compute/a-simpler-deployment-experience-with-aws-sam-cli/

Sure would be nice to see a list of proposed changes nicely formatted like that for my non function templates too- maybe thats possible and im being super dumb?

On top of that I cant use "aws cloudformation create-change-set " with a template with a function in it at all because it demands a full s3 path for CodeUri: `"StatusReason": "Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [MyFunction] is invalid. 'CodeUri' is not a valid S3 Uri of the form \"s3://bucket/key\" with optional versionId query parameter.",`

**Comment by jfuss** [comment]
@red8888 Thanks for the issue. I am going to break this down a little bit because there is a lot to unpack.

> At first sam deploy/package commands had less features then the aws cli cloudformation commands, now it seems like they have more.

`sam package|deploy` until recently has always shelled out to `aws cloudformation package|deploy`. We then ported over the implementation, so whatever AWS CLI supported in those commands were and still should be the same as SAM CLI.

> a lambda function is another resource so my expectation is I should be able to deploy it like any other cloudformation resource with "aws cloudformation" commands. I can do that but it doesn't work with all cloudformation cli features and the sam cli command has more features.

What do you mean by "doesn't work with all cloudformation cli features"? You can deploy a Lambda function with `aws cloudformation` commands directly. SAM CLI's goal is to provide a simpler means to do this. That is actually how `aws cloudformation package|deploy` started. As a side note, the `aws cloudformation package|deploy` commands are extensions in AWS CLI as they combine a bunch of Cloudformation Apis/commands together instead of interacting with a Cloudformation API directly (like `aws cloudformation create-change-set`).

> It seems like now I have to use "aws cloudformation package/deploy" commands to deploy templates unless a template has a function in it

I do not think this is true at all. Where is this claim coming from? Up until recently, SAM CLI shelled out to the `aws cloudformation package|deploy` commands for `sam package|deploy`. We ported over the guts of `aws cloudformation package|deploy` so there is no reason (that I am aware of) that would force you to use SAM CLI only for templates that have functions in them.

> For example how do I get these features for my CF templates without functions: https://aws.amazon.com/blogs/compute/a-simpler-deployment-experience-with-aws-sam-cli/

Have you tried using SAM CLI with templates that do not have functions in it?

> On top of that I cant use "aws cloudformation create-change-set " with a template with a function in it at all because it demands a full s3 path for CodeUri:

Correct. The template you are trying to deploy needs to be valid CloudFormation. Since you are using cloudformation commands directly, you will need to get the Code into S3 yourself. 

I am assuming that the Function's CodeUri is referencing a file instead of an S3 path, which is exactly what `sam package` and `aws cloudformation package` solves. The command will read the template and upload the code to S3 and replace the CodeUri with a valid S3 location. Then deploy will do the `create-change-set` call for you and also execute it, if you desire. Maybe you are doing something else? If so, can you please explain further? It's hard to tell your setup by only an error message.

This issue isn't super actionable for us. Are there features missing that you would like in `sam package|deploy`? If so, what would they be and what use case do you have for them (this will help us in understanding the problem).

**Comment by red8888** [comment]
@jfuss I didn't realize the sam commands worked on templates without functions. Also, not sure I understand how the create-change-set command works.

I was trying to run this command: 	
aws cloudformation create-change-set --region us-east-1 --template-body file://myLocalTemplateFile.yaml --stack-name mystack --change-set-name ChangeSet01 --change-set-type UPDATE --capabilities CAPABILITY_IAM --parameters ParameterKey="dddd",ParameterValue=bbbbb)

Should I upload the package with "aws cloudformation package" first and point create-change-set to the uploaded package somehow? My goal is to edit my template locally and use create-change-set to see what is going to change. Maybe Im just not using it correctly which is causing the CodeUri error?

**Comment by sriram-mv** [comment]
@red8888 You can do that today with just sam deploy --guided

One of the questions asked during `sam deploy --guided` is

```
Confirm changes before deploy [Y/n]:
```

and During the deployment it explicitly will ask you if you want to deploy the changeset after previewing the changes to you, you can choose no at that point.

```
CloudFormation stack changeset
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Operation                                                                               LogicalResourceId                                                                       ResourceType
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
* Modify                                                                                HelloWorldFunctionRole                                                                  AWS::IAM::Role
* Modify                                                                                HelloWorldFunction                                                                      AWS::Lambda::Function
* Modify                                                                                ServerlessRestApiProdStage                                                              AWS::ApiGateway::Stage
* Modify                                                                                ServerlessRestApi                                                                       AWS::ApiGateway::RestApi
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Changeset created successfully. arn:aws:cloudformation:us-east-1:abcdef:changeSet/samcli-deployabc/abc


Previewing CloudFormation changeset before deployment
======================================================
Deploy this changeset? [y/N]: n
```
