### ISSUE TITLE
Stop docker from occupying large amount of disk space

### ISSUE THREAD

**Issue by tobiasfeil** [awslabs/aws-sam-cli#1924]
I'm not a docker expert, but just ran into an alert of my disk space being full - after some investigation, I found out that `/var/lib/docker/overlay2` was 44GB large, and I only use docker for SAM. I suspect this is because every time I run my SAM application, the image is somehow duplicated on my disk (because it's not downloaded all over again as runs start very quickly). Is it possible to somehow delete old images every time `sam local invoke` is executed so disk usage is constant?

**Comment by jfuss** [comment]
@tobiasfeil Unfortunately, we have no way to know if SAM CLI downloaded the image or not. One could argue that we should delete the image after every invoke but do you really want to pay the cost of downloading the full image every single time you invoke? That would add minutes to each invoke.

My guess on what is happening, is you have a lot of dangled images. This happens when an image is downloaded but not given a new name. Historically, we have treated those the same way as any image. That is we do not remove them as we do not have a way to tell if SAM CLI downloaded them. Maybe on a flag, we can delete dangled images but we would have to figure out which ones to remove. Only ones that are from the Repository of `lambci/lambda` and that have `<none>` as tag or all dangled where Repository and tag is `<none>`? 

As you can see, this is not very clear cut and we have defaulted to customers being responsible for the docker images on the system. If you run `docker images` and see a bunch of `<none>`, you can run `docker rmi $(docker images --filter "dangling=true" -q)` which will remove all dangling images (assuming linux/mac, not sure what Windows command would exactly be).

**Comment by tobiasfeil** [comment]
Sounds good, maybe I'll just define an alias that runs the command AND deletes all dangling images every time. A flag would be awesome for this too. Thanks for taking the time!
