### ISSUE TITLE
Env var not set when value is referenced

### ISSUE THREAD

**Issue by mims92** [awslabs/aws-sam-cli#1997]
### Description

Trying to set an env var in the SAM template. The value is a reference to a cmk arn defined in the same template. The value is replaced by a default one. if the cmk arn value is set to a static string, the result is correct.

### Steps to reproduce

```Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyFunction
      CodeUri: URI
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          cmkArn:
            Fn::GetAtt:
            - DynamoDBDataKey
            - Arn
```

In python:
```
import os
def lambda_handler(event, context):
    print(os.getenv('cmkArn'))
```

### Observed result

Output: `arn:aws:lambda:us-east-1:123456789012:function:DynamoDBDataKey`
-> completely not a CMK arn

### Expected result

Output: `arn:aws:kms:{REGION}:{ACCOUNT_ID}:key/***`

if the cmkArn variable is set to a static string, the result is correct.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Debian 
2. `sam --version`: SAM CLI, version 0.49.0

**Comment by jfuss** [comment]
@mims92 Locally, we do not resolve the resource to a Resource deployed in the Cloud. In order to do that, we would have to reimplement all of CloudFormation. While I am not sure why we resolve this to a function arn, we wont be able to resolve to a specific arn for a resource. Instead, you can use the `--env-vars` option and specific the Env Var value that way.

**Comment by mims92** [comment]
Thank you @jfuss, I understand.
