### ISSUE TITLE
sam deploy does not detect changes in state machine definitions stored in S3 bucket

### ISSUE THREAD

**Issue by zgoda** [awslabs/aws-sam-cli#2019]
### Description

Since May 2020 AWS StepFunctions state machine definitions can be stored in S3 bucket instead of embedding them in template. Changes to definitions stored in S3 bucket are not detected and `sam deploy` rejects stack updates because "there was no change to stack".

### Steps to reproduce

Create AWS StepFunctions state machine definition in JSON file
Define state machine in template, specifying `DefinitionS3Location`
Upload state machine definition to S3
Run deployment
Change state machine definition
Upload changed state machine definition
Run deployment

### Observed result

`Error: No changes to deploy. Stack mystack is up to date`.

State machine is not updated.

### Expected result

State machine is updated with new definition.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux Ubuntu 20.04
2. `sam --version`: `SAM CLI, version 0.52.0`

`Add --debug flag to command you are running`

Relevant lines:

```
Property DefinitionS3Location of MyStateMachine resource is not a URL
File with same data is already exists at <somehash>.template. Skipping upload
```

**Comment by jfuss** [comment]
@zgoda Did you update the object in S3 or did you create a new object? Are you uploading to S3 directly or using `sam package` or `sam deploy` on a template that requires packaging (aka the value points to a local file instead of S3).

I believe that CloudFormation, determines updates based on the template not the contents of the object in S3. If that is true and you only updated the object instead of creating a new one, then the behavior makes sense.

**Comment by zgoda** [comment]
PEBKAC
