### ISSUE TITLE
Support Python3

### ISSUE THREAD

**Issue by include** [awslabs/aws-sam-cli#387]
hi,

Moments ago I've removed the old npm sam cli and upgraded to the latest with pip when I realised this is a python2 app. Are any plans to add python3 support to it?

Thanks in advance;; and thanks a lot for this sam-cli/local :)

Cheers,
Francisco

**Comment by jfuss** [comment]
@include Yes. We some of our dependencies are not built for py3 just yet. We are working resolving this. We built the CLI to be py3 compatible from the start, just need all dependencies to support py3 first :)

**Comment by sanathkr** [comment]
Yes! Python3 support is coming soon (not dates yet but definitely happening). We were aware of this limitation at launch but wanted to deliver all the exciting new features first rather than holding off for Python3. 

I will update the Issue title to be more descriptive of the question and use this as a tracking issue.

**Comment by kadrach** [comment]
A simple warning like
```sh
$ sam
This tool does not support python3, please install python2.
```
would be nice :)

**Comment by josephmcasey** [comment]
Adding onto the point by @kadrach. It would be nice if there was a warning in the documentation that AWS CLI also needs to be using Python 2 and not Python 3.6.5

**Comment by jfuss** [comment]
@josephmcasey We have a very small note in the README.rst about this: https://github.com/awslabs/aws-sam-cli#windows-linux-macos-with-pip-recommended. I agree it can be clearer and should be but we are quickly working towards Py3 for both SAM CLI and [SAM](https://github.com/awslabs/serverless-application-model/pull/428). 

While adding this into the cli would be nice @kadrach, it is not possible since you wouldn't be able to `pip install` it.

**Comment by jfuss** [comment]
Happy to close this and say Py3.6 is supported in [v0.4.0](https://github.com/awslabs/aws-sam-cli/releases/tag/v0.4.0)!

Closing

**Comment by rogthedodge** [comment]
Fabulous - can you tell me how I install it from the zip or gz file rather than pip please?
