### ISSUE TITLE
pip sucks

### ISSUE THREAD

**Issue by tleef** [awslabs/aws-sam-cli#388]
Seriously, I have never had anything but problems with pip. 

The issue, imo, is python has too many ways of doing things which aren't very compatible. For example, you have issues out of the gate with 2.7 vs 3. Did people install python with Homebew (mac)? Are they using the default version of python included with the machine? Are they using PyEnv or something else? There are so many environmental factors to consider and troubleshoot. At the end of the day, this leads to frustration for users and wasted cycles on something that should be simple.

To be fair, maybe I'm not using pip in the best way. I'm not really a python dev and I don't keep up with python best practices all that much but at the same time, I shouldn't need to just to install a cli tool.

I think the length of the update README section covering installing/updating/troubleshooting with pip speaks for itself.

Solution, stick to npm for distribution.

**Comment by jfuss** [comment]
@tleef Let's try to keep this positive. I understand the frustration and we will be working towards making the experience easier as we progress.

Closing this issue as it is not actionable.

**Comment by sanathkr** [comment]
Or an alternative solution is to build installers like .msi or .dmg that can install the entire tool for you without needing PIP. This is an option we are exploring for the subsequent releases so you don’t need pip. 

But hey, I hear your about PIP dude. They have done a lot of improvements lately and a lot of cool advancements coming in Future.

**Comment by jfuss** [comment]
@tleef We totally get it! The reason I marked un-actionable was due to the tone of the issue not that we do not want to make this simpler and invest here. If you are willing to update the title and parts of the description, I would be more than willing to re-open the issue and have a deeper discussion with you and the rest of the community, or even a new issue because I do feel this is am important thing we should be addressing.

"I know distribution isn't the most sexy part of maintaining an open source project but I think its one of the most important parts." Absolutely!!! It is the entry point to the CLI. If customers have trouble trying to install, then its completely possible they will go find some other tool to use instead. The team wants to make sure all platforms can install the CLI and make this as painless as possible. We landed on PIP initially because it was the easiest thing to support at the start and the supported way for Python. We quickly realize through testing and discussing with others that only supporting PIP might not the right long term thing for our customers. Pip is still evolving and things like [PipEnv](https://github.com/pypa/pipenv) are focused on solving the distribution problems in the Python community. 

In the previous version, we still had issues with customers installing the CLI through NPM. While I am only going off of issues I have seen (I don't know much about NPM myself), there has still been a fair amount of trouble getting the CLI installed. So I don't think this is as clear as one way is better than the other.

Given the CLI is in Python, I don't see us moving away from PIP but do see us finding and allowing other ways for customers to install the CLI.

**Comment by jfuss** [comment]
@kay-is Make sure where sam in installed is in your PATH. When using the '--user', it can be placed in a path that is not in your $PATH. We are working on updating the README with these instructions.

1) Find your path Python User Base path (where Python --user will install packages/scripts): python -m site --user-base
2) Add that path under your PATH variable

You can also try without --user `pip install aws-sam-cli`

**Comment by blexo** [comment]
May I ask why you're not using the npm installer?  I am just trying to get going on an alexa skill - got no probs uploading the zip directly to the lambda tool but want to automate and I've wasted an hour messing with pip...  super annoying.  It does not seem to like mac at all.
