### ISSUE TITLE
Function without Event section pointed to API?

### ISSUE THREAD

**Issue by terma** [awslabs/aws-sam-cli#507]
Hi team,

I can't find in doc, case when you have defined API with ref to Function, but Function doesn't have ```event``` section pointed to API.

What will be result of that?

From my point of view it will be invalid configuration when API will not have enough permissions to call Function.

Thx,

**Comment by sanathkr** [comment]
You should post this in SAM Repository https://github.com/awslabs/serverless-application-model 

But since you posted here: This will connect your API to your Function inside APIGW service. But since the event section isn't there, your API won't have permissions to invoke this Function (Unless you added permission separately)
