### ISSUE TITLE
DefinitionUri do not perform variable replacement magic

### ISSUE THREAD

**Issue by ronaldwidha** [awslabs/aws-sam-cli#691]
Perhaps this is a bug/feature request for the Cloudformation team. Unlike `DefinitionBody`, `DefinitionUri` as CloudFormation will only reference the external file, but not do any of it's variable replacement magic (resource logical IDs, or resource attributes). Is this by design? seems inconsistent. Should the SAM CLI flatten the referenced Swagger file into DefinitionBody as part of `package`?

**Comment by jfuss** [comment]
What you described is a CloudFormation limitation. CloudFormation will not resolve these and since SAM is built on top of CloudFormation, SAM has the same limitation. 

We shouldn't be pulling this reference into the `DefinitionBody`. Customers move their Swagger files into S3 to lower the size of their templates. Instead, you should add this into the template directly if that solves the problem.

Closing this as we are bound to CloudFormation's limitation on this.
