### ISSUE TITLE
"sam init" while passing in location ignores "name" parameter

### ISSUE THREAD

**Issue by rli** [awslabs/aws-sam-cli#757]
**Description:**

While using `sam init` with a --location parameter and --no-input, --name is allowed, but ignored

**Steps to reproduce the issue:**
1. `sam init --location gh:aws-samples/cookiecutter-aws-sam-dynamodb-python --no-input --name agoodname`

**Observed result:**
```
[+] Initializing project structure...
Error: An error occurred while generating this agoodname: Error: "dynamodb_event_reader" directory already exists
```

**Expected result:**
One of:
* error due to --name not being allowed with --no-input
* success, and a new directory named 'agoodname'

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
Mac

**Output of `sam --version`**:
SAM CLI, version 0.6.2

Another good option to have: to be able to specify cookiecutter parameters in the command-line arguments alongside --no-input, so that certain options can be overridden and defaults taken for unspecified parameters.

**Comment by heitorlessa** [comment]
hey @rli --- Thanks for opening this up. That was initially on purpose as ``--location`` implies the custom cookiecutter you're pointing too will be in control of what the generated folder will be. 

``--location`` will actually ignores all other parameters due to the reason above. 

I thought about allowing additional args to the destined template but I also found that power users would prefer to use a cookiecutter user config either way.

Happy to hear your thoughts on this

**Comment by rli** [comment]
Okay, it looks like the [config file](https://cookiecutter.readthedocs.io/en/latest/advanced/user_config.html) solves our use case. We are executing SAM CLI on behalf of the user, so it would be nice to not have to generate a config file for template init, but is already what we are doing for sam local invoke/debug.

It would be great if this were documented in `sam init --help`, as it is not clear that config file overrides for cookiecutter was even an option.

**Comment by jfuss** [comment]
@heitorlessa Is there something else other than the config file we can do here? I don't want to introduce a frameworks config into SAM CLI, as this couples them together.

**Comment by heitorlessa** [comment]
We do Jacob - Allowing —name along with location by overriding output_dir.

I don’t think we should support cookiecutter config/extra parameters  as
that indeed is engine specific and that will need to be maintained over
time, since that introduce side effects too as they update mainstream
cookiecutter.

For all edge cases one can use cookiecutter user config without having us
to change or introduce new SAM CLI code

**Comment by heitorlessa** [comment]
hey @rli -- Jacob and I just had a chat on this.

Besides the ``name`` option that should be fixed, if we provide something like ``--extra-context`` so you can control additional key/value for custom templates... would that suffice in your case?

I just tested using the latest version and extra-context doesn't make it fail compared to what is was before so it's safe to do that. Worst it can happen is that additional context doesn't get used by the target template. 

On the ``--name`` I'd need to make sure it would always override the target directory regardless on what template one wants to use and if that's the case I'm happy to make a PR to address both

**Comment by rli** [comment]
@heitorlessa that sounds great, Thank you!

**Comment by heitorlessa** [comment]
@rli PR pushed and waiting for CR.

New PR introduces `-e` and `--extra-context` in addition to respecting `--name` with ``--location``. 

When using custom templates with --location you can now pass additional context so that you can have `a --no-input` experience:

```bash
samdev init \
    --name Something \
    -e runtime=python3.6 \
    --location https://github.com/aws-samples/cookiecutter-aws-sam-dynamodb-python \
    --no-input
```

You can pass multiple context by adding multiple `-e` entries:

```bash
samdev init \
    --name Something \
    -e runtime=python3.6 \
    -e ignore=me \
    --location https://github.com/aws-samples/cookiecutter-aws-sam-dynamodb-python \
    --no-input
```

Help text from ``sam init --help`` has been updated to reflect that too

**Comment by buggy** [comment]
@heitorlessa Using `--runtime RUNTIME` with built-in templates but `-e runtime=RUNTIME` for custom templates feels like it complicates the situation with no benefit. One of the use cases for custom templates is new languages that use existing runtimes. I found my way here after trying to build a custom template for TypeScript and discovering the `--name` and `--runtime` properties weren't being passed through.

Passing the `--runtime` keeps it consistent.

Default template:
```sh
sam init \
  --name something \
  --runtime nodejs8.10 \
```

Custom template:
```
sam init \
  --name something \
  --runtime nodejs8.10 \
  --location https://github.com/my-repo/cookiecutter-aws-sam-typescript
```

At this stage it's easy enough to tell template developers the `project_name` and `runtime` will both be passed as extra parameters and they can ignore them if they don't want to use them.

**Comment by heitorlessa** [comment]
Done - ``runtime`` gets passed as extra context

**Comment by sriram-mv** [comment]
Going to close the issue, since https://github.com/awslabs/aws-sam-cli/pull/1500 addresses most of the concerns here.
